export const ADD_FRIEND = 'ADD_FRIEND';
export const DELETE_FRIEND = 'DELETE FRIEND';
export const SEARCH_FRIEND = 'SEARCH_FRIEND';
export const FAVORITE_FRIEND = 'FAVORITE_FRIEND';
export const NEXT_PAGE = 'NEXT_PAGE';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';
